# Generated by Django 5.2.7 on 2025-10-30 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_farm_last_sensed_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advisory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_id', models.CharField(db_index=True, max_length=50)),
                ('field_name', models.CharField(max_length=255)),
                ('field_area', models.DecimalField(decimal_places=3, max_digits=10)),
                ('field_area_unit', models.CharField(default='acres', max_length=20)),
                ('crop', models.CharField(max_length=100)),
                ('sowing_date', models.DateField()),
                ('timestamp', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sar_day', models.CharField(max_length=20)),
                ('sensed_day', models.DateField()),
                ('last_satellite_visit', models.CharField(max_length=50)),
                ('raw_response', models.JSONField(default=dict)),
                ('satellite_data', models.JSONField(default=dict)),
                ('advisory_data', models.JSONField(default=dict)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisories', to='users.farm')),
            ],
            options={
                'db_table': 'advisories',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['farm', '-created_at'], name='advisories_farm_id_1fea9b_idx'), models.Index(fields=['field_id', '-created_at'], name='advisories_field_i_1f6375_idx'), models.Index(fields=['crop', '-created_at'], name='advisories_crop_5cf536_idx')],
                'unique_together': {('farm', 'sensed_day')},
            },
        ),
    ]
