# Generated by Django 5.2.7 on 2025-10-30 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_farm_last_sensed_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossLossAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('flood', 'Flood Scenario'), ('drought', 'Drought Case'), ('pest', 'Pest Case')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('date_start', models.DateField()),
                ('date_current', models.DateField()),
                ('date_end', models.DateField()),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.farm', verbose_name='Crop Loss Analytics')),
            ],
            options={
                'unique_together': {('farm', 'kind')},
            },
        ),
    ]
