# Generated by Django 5.2.7 on 2025-10-30 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crop_loss_analytics', '0001_initial'),
        ('users', '0002_alter_farm_last_sensed_day'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CrossLossAnalytics',
            new_name='CropLossAnalytics',
        ),
    ]
