# Generated by Django 5.2.7 on 2025-11-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop_loss_analytics', '0002_rename_crosslossanalytics_croplossanalytics'),
        ('users', '0003_alter_farm_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='croplossanalytics',
            unique_together={('farm', 'kind', 'is_active')},
        ),
        migrations.AddField(
            model_name='croplossanalytics',
            name='closest_date_sensed',
            field=models.DateField(default='2025-11-03'),
            preserve_default=False,
        ),
    ]
