# Generated by Django 5.2.7 on 2025-11-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop_loss_analytics', '0003_alter_croplossanalytics_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='croplossanalytics',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
