# Generated by Django 5.2.7 on 2025-10-30 13:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_farm_last_sensed_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_reload', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('summary', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('main', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=10)),
                ('temp_day', models.FloatField()),
                ('temp_min', models.FloatField()),
                ('temp_max', models.FloatField()),
                ('temp_morn', models.FloatField()),
                ('temp_eve', models.FloatField()),
                ('temp_night', models.FloatField()),
                ('feels_like_day', models.FloatField()),
                ('feels_like_morn', models.FloatField()),
                ('feels_like_eve', models.FloatField()),
                ('feels_like_night', models.FloatField()),
                ('humidity', models.FloatField()),
                ('pressure', models.FloatField()),
                ('dew_point', models.FloatField()),
                ('uvi', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('wind_deg', models.IntegerField()),
                ('wind_gust', models.FloatField(blank=True, null=True)),
                ('clouds', models.IntegerField()),
                ('pop', models.FloatField()),
                ('rain', models.FloatField(blank=True, null=True)),
                ('sunrise', models.BigIntegerField()),
                ('sunset', models.BigIntegerField()),
                ('moonrise', models.BigIntegerField()),
                ('moonset', models.BigIntegerField()),
                ('moon_phase', models.FloatField()),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_prediction', to='users.farm')),
            ],
            options={
                'ordering': ['date'],
                'indexes': [models.Index(fields=['date_of_reload', 'date'], name='weather_wea_date_of_78075b_idx')],
                'unique_together': {('farm', 'date_of_reload', 'date')},
            },
        ),
    ]
