# Generated by Django 5.2.7 on 2025-10-30 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_farm_last_sensed_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heatmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_type', models.CharField(choices=[('rvi', 'RVI'), ('ndvi', 'NDVI'), ('savi', 'SAVI'), ('evi', 'EVI'), ('ndre', 'NDRE'), ('rgb', 'RGB'), ('rsm', 'RSM'), ('ndwi', 'NDWI'), ('ndmi', 'NDMI'), ('et', 'ET'), ('soc', 'SOC')], max_length=10)),
                ('date', models.DateField()),
                ('image_url', models.URLField(max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heatmaps', to='users.farm')),
            ],
            options={
                'db_table': 'heatmaps',
                'unique_together': {('farm', 'index_type', 'date')},
            },
        ),
        migrations.CreateModel(
            name='IndexTimeSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_type', models.CharField(choices=[('rvi', 'RVI - Ratio Vegetation Index'), ('ndvi', 'NDVI - Normalized Difference Vegetation Index'), ('savi', 'SAVI - Soil Adjusted Vegetation Index'), ('evi', 'EVI - Enhanced Vegetation Index'), ('ndre', 'NDRE - Normalized Difference Red Edge'), ('rgb', 'RGB - True Color Composite'), ('rsm', 'RSM - Root Zone Soil Moisture'), ('ndwi', 'NDWI - Normalized Difference Water Index'), ('ndmi', 'NDMI - Normalized Difference Moisture Index'), ('et', 'ET - Evapotranspiration'), ('soc', 'SOC - Soil Organic Carbon')], max_length=10)),
                ('date', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_time_series', to='users.farm')),
            ],
            options={
                'db_table': 'index_time_series',
                'ordering': ['date'],
                'unique_together': {('farm', 'index_type', 'date')},
            },
        ),
    ]
