# Generated by Django 5.2.7 on 2025-10-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heatmaps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heatmap',
            name='index_type',
            field=models.CharField(choices=[('rvi', 'RVI'), ('ndvi', 'NDVI'), ('savi', 'SAVI'), ('evi', 'EVI'), ('ndre', 'NDRE'), ('rsm', 'RSM'), ('ndwi', 'NDWI'), ('ndmi', 'NDMI'), ('evapo', 'ET'), ('soc', 'SOC'), ('etci', 'ETCI')], max_length=10),
        ),
        migrations.AlterField(
            model_name='indextimeseries',
            name='index_type',
            field=models.CharField(choices=[('rvi', 'RVI - Ratio Vegetation Index'), ('ndvi', 'NDVI - Normalized Difference Vegetation Index'), ('savi', 'SAVI - Soil Adjusted Vegetation Index'), ('evi', 'EVI - Enhanced Vegetation Index'), ('ndre', 'NDRE - Normalized Difference Red Edge'), ('rsm', 'RSM - Root Zone Soil Moisture'), ('ndwi', 'NDWI - Normalized Difference Water Index'), ('ndmi', 'NDMI - Normalized Difference Moisture Index'), ('evapo', 'ET - Evapotranspiration'), ('soc', 'SOC - Soil Organic Carbon'), ('etci', 'ETCI')], max_length=10),
        ),
    ]
