# Generated by Django 5.2.7 on 2025-11-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heatmaps', '0002_alter_heatmap_index_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heatmap',
            name='index_type',
            field=models.CharField(choices=[('rvi', 'RVI'), ('ndvi', 'NDVI'), ('savi', 'SAVI'), ('evi', 'EVI'), ('ndre', 'NDRE'), ('rsm', 'RSM'), ('ndwi', 'NDWI'), ('ndmi', 'NDMI'), ('evapo', 'ET'), ('soc', 'SOC'), ('etci', 'ETCI'), ('hybrid', 'HYBRID')], max_length=10),
        ),
    ]
